# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('time', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=20)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_info', models.CharField(max_length=20)),
                ('remote_status', models.CharField(max_length=20)),
                ('call', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('status', models.CharField(choices=[('PENDING_OPEN', 'PENDING_OPEN'), ('OPEN', 'OPEN'), ('PENDING_CLOSE', 'PENDING_CLOSE'), ('CLOSE', 'CLOSE')], default='PENDING_OPEN', max_length=20)),
                ('time', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=20)),
                ('series', models.CharField(max_length=2)),
                ('open', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prevclose', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tottrdqty', models.IntegerField(default=0)),
                ('tottrdval', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('totaltrades', models.IntegerField(default=0)),
                ('isin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('budget', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='INACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('train_details', models.TextField(default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('FLUSH', 'FLUSH')], default='INACTIVE', max_length=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Stock')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Strategy')),
            ],
        ),
        migrations.AddField(
            model_name='strategy',
            name='stocks',
            field=models.ManyToManyField(through='harvest.Watchlist', to='harvest.Stock'),
        ),
        migrations.AddField(
            model_name='signal',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Stock'),
        ),
        migrations.AddField(
            model_name='signal',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Strategy'),
        ),
        migrations.AddField(
            model_name='order',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Signal'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Stock'),
        ),
        migrations.AddField(
            model_name='order',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Strategy'),
        ),
    ]
