# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='percent_low',
            field=models.IntegerField(default=0),
        ),
    ]
