# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_auto_20171110_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='signal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='harvest.Signal'),
        ),
    ]
