# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0004_auto_20171110_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='signal_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('FLUSH', 'FLUSH')], default='CLOSE', max_length=20),
        ),
    ]
