# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0005_watchlist_signal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desc', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harvest.Signal')),
            ],
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='budget',
        ),
        migrations.AlterField(
            model_name='order',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Signal'),
        ),
    ]
