# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0007_ledger_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='last_buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='last_buy_qty',
            field=models.IntegerField(default=0),
        ),
    ]
