# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-11 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0008_auto_20171111_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='last_buy_price',
            new_name='last_price',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='last_buy_qty',
            new_name='last_qty',
        ),
    ]
