# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0010_auto_20171111_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='signal_status',
            field=models.CharField(choices=[('PENDING_OPEN', 'PENDING_OPEN'), ('OPEN', 'OPEN'), ('PENDING_CLOSE', 'PENDING_CLOSE'), ('CLOSE', 'CLOSE'), ('NONE', 'NONE')], default='NONE', max_length=20),
        ),
    ]
