# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0011_ledger_signal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harvest.Order'),
        ),
    ]
