# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0012_ledger_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='call',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='remote_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
