# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0013_auto_20171115_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='signal_status',
            field=models.CharField(choices=[('PENDING_OPEN', 'PENDING_OPEN'), ('OPEN', 'OPEN'), ('PENDING_CLOSE', 'PENDING_CLOSE'), ('CLOSE', 'CLOSE'), ('NONE', 'NONE')], default='NONE', max_length=20, null=True),
        ),
    ]
