# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0014_auto_20171206_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ndaylow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_trade_val', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('avg_hold_inter', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('n_day_low', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('return_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('score', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('norm_score', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Stock')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.Strategy')),
            ],
        ),
    ]
