# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0015_ndaylow'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndaylow',
            name='allocation',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
