# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0016_ndaylow_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='hold_active_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='profit_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
