# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0017_auto_20171212_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='close_type',
            field=models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default='SELL', max_length=10),
        ),
    ]
